permalink: pretty
highlighter: pygments
markdown: kramdown
kramdown:
    input: GFM
    toc_levels: 2..6

exclude:
    - _build
    - Gemfile*
    - CNAME
    - README.md

gems:
    - jekyll-redirect-from
    - jekyll-sitemap
