markdown: kramdown
kramdown:
    input: GFM
    toc_levels: 2..6

exclude: [_build]

# below waiting on domain rework

#gems:
#    - jekyll-redirect-from
#    - jekyll-sitemap

# https://github.com/jekyll/jekyll-redirect-from
# case insensitive