baseurl: /docs.montagestudio.com

highlighter: pygments
markdown: kramdown
kramdown:
    input: GFM
    toc_levels: 2..6

exclude:
    - _build
    - Gemfile*
    - CNAME
    - README.md

gems:
    - jekyll-redirect-from
    - jekyll-sitemap

# TODO: permalink: pretty
# can't yet due to jsdoc generating links to html pages
